// Code generated by goctl. DO NOT EDIT.
package types

type TradingViewHookRequest struct {
	Name string `json:"name,options=you|me"`
}

type TradingViewHookResponse struct {
	Message string `json:"message"`
}
