// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"trader/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/hookTrading",
				Handler: TradingviewHookHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/test",
				Handler: TraderHandlerGetHandler(serverCtx),
			},
		},
	)
}
